[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[project]
name = 'TTStatistics'
version = '0.0.1'
authors = [
    {name = 'Daniel Hall', email = 'blankemail@email.com'},
]
description = "A dice statistics module"
readme = 'README.md'
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.0.0",
    "scipy>=1.14.1"
]

[project.urls]
Homepage = "https://github.com/daplhall/TTStatistics"
Issues = "https://github.com/daplhall/TTStatistics/issues"

[tool.hatch.build.targets.sdist]
include = [
  "TTStatistics/*",
  "tests/*"
]